export enum ChatSettingsWindowActions {
    LOAD_CONTENT,

    CHANGE_AUTO_RESPONDER_ENABLED,
    CHANGE_FLOODING_ENABLED,
    CHANGE_INACTIVE_TIMER,

    CHANGE_PRIVATE_CHAT_RESPONSE,
    CHANGE_COMMON_CHAT_RESPONSE,
    CHANGE_TRADE_CHAT_RESPONSE,
    CHANGE_GROUP_CHAT_RESPONSE,
    CHANGE_CLAN_CHAT_RESPONSE,
    CHANGE_ALLIANCE_CHAT_RESPONSE,

    CHANGE_COMMON_CHAT_FLOODING_MESSAGE,
    CHANGE_COMMON_CHAT_FLOODING_TIMER,

    CHANGE_TRADE_CHAT_FLOODING_MESSAGE,
    CHANGE_TRADE_CHAT_FLOODING_TIMER,

    CHANGE_GROUP_CHAT_FLOODING_MESSAGE,
    CHANGE_GROUP_CHAT_FLOODING_TIMER,

    CHANGE_CLAN_CHAT_FLOODING_MESSAGE,
    CHANGE_CLAN_CHAT_FLOODING_TIMER,

    CHANGE_ALLIANCE_CHAT_FLOODING_MESSAGE,
    CHANGE_ALLIANCE_CHAT_FLOODING_TIMER,

    SAVE
}
