export enum DressingWindowActions {
    LOAD_CONTENT,
    CREATE_NEW_SET,
    SAVE_SET,
    REMOVE_SET,
    SELECT_SET,

    SELECT_PLACEHOLDER,
    DESELECT_PLACEHOLDER,

    UNEQUIP_ITEM,
    UNEQUIP_ALL,
    EQUIP,
    EQUIP_FROM_SET,

    ADD_FILTER,
    REMOVE_FILTER
}