export enum NotificationsWindowActions {
    LOAD_CONTENT,
    CHANGE_FIGHT_NOTIFICATIONS_SYSTEM,
    CHANGE_FIGHT_NOTIFICATIONS_INGAME,
    CHANGE_BATTLEGROUND_NOTIFICATIONS_SYSTEM,
    CHANGE_BATTLEGROUND_NOTIFICATIONS_INGAME,
    CHANGE_MESSAGE_NOTIFICATIONS_SYSTEM,
    CHANGE_MESSAGE_NOTIFICATIONS_INGAME,
    CHANGE_MAIL_NOTIFICATIONS_SYSTEM,
    CHANGE_MAIL_NOTIFICATIONS_INGAME,
    CHANGE_EXPIRING_ITEMS_NOTIFICATIONS_SYSTEM,
    CHANGE_EXPIRING_ITEMS_NOTIFICATIONS_INGAME,
    SAVE_SETTINGS
}
