export type ClientSettings = {
    server: string
    baseUrl: string
    mailServer: boolean
    ownServer: string
    windowOpenNewTab: boolean
    windowsAboveApp: boolean
    selectedUserAgentType: string
    selectedUserAgentValue: string
    maximizeOnStart: boolean
    hideTopPanelInFullScreen: boolean
    animationSpeedType: string
    fightNotificationsSystem: boolean
    fightNotificationsIngame: boolean
    fightFinishedNotificationsSystem: boolean
    fightFinishedNotificationsIngame: boolean
    battlegroundNotificationsSystem: boolean
    battlegroundNotificationsIngame: boolean
    messageNotificationsSystem: boolean
    messageNotificationsIngame: boolean
    mailNotificationsSystem: boolean
    mailNotificationsIngame: boolean
    expiringItemsNotificationsSystem: boolean
    expiringItemsNotificationsIngame: boolean
    resourceFarmingFinishedNotificationSystem: boolean
    resourceFarmingFinishedNotificationIngame: boolean
    updateChannel: string
    needToRestoreUrls: boolean
    restoreUrls: string[]
}
