export enum SettingsWindowActions {
    LOAD_SETTINGS,
    SAVE_SETTINGS,
    SAVE_SHORTCUTS,
    CHANGE_USER_AGENT,
    CHANGE_WINDOW_OPEN_NEW_TAB,
    CHANGE_WINDOWS_ABOVE_APP,
    CHANGE_MAXIMIZE_ON_START,
    CHANGE_HIDE_TOP_PANEL_IN_FULL_SCREEN,
    CHANGE_ANIMATION_SPEED_TYPE,
    CHANGE_MAIL_SERVER,
    CHANGE_UPDATE_CHANNEL,
    CHANGE_NEED_TO_RESTORE_URLS
}
